events { }

http {
    # 1. Définition des serveurs en amont (Docker Services)
    upstream streaming_backend {
        #server bambaiba_streaming:7000;
		server host.docker.internal:7000;
    }

    upstream studio_backend {
		#server bambaiba_studio:7002;    # Nom du service docker-compose
        server host.docker.internal:7002;
    }

    upstream seaweedfs_backend {
		#server bambaiba_seaweedfs:8888; # Ou le nom de ton service SeaweedFS
        server host.docker.internal:8888;
    }

    server {
        listen 80;
		
		client_max_body_size 1G; 
        # ---------------------------------------------------------
        # ROUTE 1 : STUDIO (Upload & Gestion)
        # ---------------------------------------------------------
        # Toute requête commençant par /studio/ va vers l'API Studio
        location /studio/ {
            # On passe l'URL telle quelle (ex: /studio/upload)
            # Car ton code C# a MapGroup("/studio")
            proxy_pass http://studio_backend/;
			
			proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            
            # Headers importants
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Support des WebSockets (utile pour SignalR si utilisé dans Studio)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # ---------------------------------------------------------
        # ROUTE 2 : MEDIA (Images & Vidéos)
        # ---------------------------------------------------------
        # Toute requête commençant par /media/ va vers SeaweedFS
        location /media/ {
            # Réécriture : /media/chemin... devient /buckets/chemin...
            rewrite ^/media/(.*)$ /buckets/$1 break;
            
            proxy_pass http://seaweedfs_backend;
            
            # Cache côté Nginx (optionnel mais recommandé)
            expires 7d;
            add_header Cache-Control "public";
			client_max_body_size 100M;
        }

        # ---------------------------------------------------------
        # ROUTE 3 : STREAMING (Public par défaut)
        # ---------------------------------------------------------
        # Tout le reste va vers l'API Streaming
        location /streaming/ {
            proxy_pass http://streaming_backend/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Support des WebSockets (Pour les Hubs SignalR : Chat, Notifications)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
