events { }

http {
    # Upstream : Définition de tes services (Docker network names ou localhost)
    upstream api_backend {
        # server localhost:7000; 
		server host.docker.internal:7000; # Ou "bambaiba-api:7000" si dans le même docker-compose
    }

    upstream seaweedfs_backend {
        # server localhost:8888; 
		server host.docker.internal:8888; # Ou "seaweedfs-filer:8888"
    }

    server {
        listen 80;
		
		# ssl_certificate /etc/nginx/certs/fullchain.pem;
        # ssl_certificate_key /etc/nginx/certs/privkey.pem;

        # 1. ROUTAGE API (.NET)
        # Tout ce qui commence par /api/ va vers l'API C#
        location /api/ {
            proxy_pass http://api_backend/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. ROUTAGE MEDIA (SeaweedFS)
        # Tout ce qui commence par /media/ va vers SeaweedFS
        # Exemple: GET /media/bambaiba-images/monimage.jpg
        location /media/ {
            # On réécrit l'URL pour ajouter /buckets/ automatiquement avant d'envoyer à SeaweedFS
            # /media/bambaiba-images/img.jpg devient /buckets/bambaiba-images/img.jpg
            rewrite ^/media/(.*)$ /buckets/$1 break;

            proxy_pass http://seaweedfs_backend;
            
            # Cache côté Nginx (Optionnel mais recommandé pour les images)
            expires 7d;
            add_header Cache-Control "public";
            
            # Augmenter la taille max d'upload si besoin pour de gros fichiers
            client_max_body_size 100M;
        }
        
        # 3. Route par défaut (Optionnel : Frontend React/Vue)
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}
